# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Another Useless Game Dev Diary
email: virtualcollapsar@gmail.com
description: > 
    Welcome to another useless game dev log! This blog talks about 
    every kind games related things, from tutorial to experiences and
    rant!
baseurl: "" # subpath e.g. /blog
url: "https://uselessdevlog.github.io" 
#url: "http://127.0.0.1:4000" # local
twitter_username: giosaffi
github_username:  UselessDevLog

# Plugins setting
gems: ['jekyll-paginate', 'jekyll-feed', 'jekyll-sitemap', 'jekyll/tagging', 'jekyll-tagging-related_posts']

# Post permalink
permalink: "/:categories/:title"

# Pagination settings
paginate: 9
paginate_path: "/home/page:num/"

# Build settings
markdown: kramdown
highlighter: rouge

# Repository
repository: "UselessDevLog/uselessdevlog.github.io"

# Keep File
keep_files: ["images"]

# Include
include: [".htaccess"]

# Seo Config
twitter:
    page: uselessdevlog

fb:
    #admins: nothing
    #publisher: nothing
    app_id: 0000
    page: uselessdevlog
    
#google_verification: 

# Source Images
images:
    defualt: "https://uselessdevlog.github.io/images/"
    member: "https://uselessdevlog.github.io/images/member/"
    hero: "https://uselessdevlog.github.io/images/hero/"
    mini: "https://uselessdevlog.github.io/images/hero/thumb/th-"
    site: "https://uselessdevlog.github.io/images/site.jpg"